outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  podcast:
    mediaType: "application/rss+xml"
    baseName: "podcast"

module:
  imports:
    - path: github.com/twitter/twemoji
      mounts:
        - source: assets/svg
          target: static/twemoji/svg
