  
name = "tatsu"
license = "MIT"
licenselink = "https://github.com/sambacha/tatsu/raw/branch/master/LICENSE.md"
description = "jlelse's personal Hugo theme"
homepage = "https://github.com/sambacha/tatsu"
tags = []
features = []

[author]
  name = "tatsu"
  homepage = "https://sambacha.github.io"
